use std::collections::TryReserveError;
use std::iter::FusedIterator;
use std::ops::Range;

use thiserror::Error;
use unity_asset_core::{
    AllocationSizeError, AssetLoadBudget, BudgetError, DigestV1, vec_allocation_bytes,
};

use crate::artifact::{ArtifactPayload, ArtifactPayloadProvenance};

/// Flags retained with a streamed-resource artifact for its containing format node.
///
/// The bit layout belongs to the enclosing Unity container (AssetBundle or WebFile), so this
/// module deliberately treats the value as opaque while still avoiding an unlabelled `u32` in
/// resource planning APIs.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash)]
pub struct StreamedResourceFlags(u32);

impl StreamedResourceFlags {
    #[must_use]
    pub const fn new(bits: u32) -> Self {
        Self(bits)
    }

    #[must_use]
    pub const fn bits(self) -> u32 {
        self.0
    }
}

impl From<u32> for StreamedResourceFlags {
    fn from(bits: u32) -> Self {
        Self::new(bits)
    }
}

/// One borrowed payload to place in a streamed-resource sidecar.
#[derive(Debug, Clone)]
pub(super) enum ExtentPayload<'payload> {
    Generated(&'payload [u8]),
    Artifact(&'payload ArtifactPayload),
    ArtifactRange {
        payload: &'payload ArtifactPayload,
        range: Range<usize>,
    },
}

/// One resource extent and its required alignment.
///
/// Extents are borrowed intentionally.  The caller (usually the workspace mutation overlay)
/// remains the owner of input bytes; the artifact transaction only retains the exact source ranges
/// or generated chunks that are reachable from a committed output.
#[derive(Debug, Clone)]
pub struct StreamedResourceExtent<'payload> {
    payload: ExtentPayload<'payload>,
    alignment: u32,
    length: u32,
}

impl<'payload> StreamedResourceExtent<'payload> {
    /// Creates an extent backed by newly generated bytes.
    pub fn generated(
        bytes: &'payload [u8],
        alignment: u32,
    ) -> Result<Self, StreamedResourcePlanError> {
        validate_alignment(alignment)?;
        let length = checked_size_usize(bytes.len())?;
        Ok(Self {
            payload: ExtentPayload::Generated(bytes),
            alignment,
            length,
        })
    }

    /// Creates an extent backed by a complete immutable artifact payload.
    pub fn artifact_payload(
        payload: &'payload ArtifactPayload,
        alignment: u32,
    ) -> Result<Self, StreamedResourcePlanError> {
        validate_alignment(alignment)?;
        let length = checked_size_u64(payload.len())?;
        Ok(Self {
            payload: ExtentPayload::Artifact(payload),
            alignment,
            length,
        })
    }

    /// Creates an extent backed by a zero-copy range of an immutable artifact payload.
    pub fn artifact_payload_range(
        payload: &'payload ArtifactPayload,
        range: Range<usize>,
        alignment: u32,
    ) -> Result<Self, StreamedResourcePlanError> {
        validate_alignment(alignment)?;
        let payload_len = usize::try_from(payload.len()).map_err(|_| {
            StreamedResourcePlanError::PayloadLengthOverflow {
                length: payload.len(),
            }
        })?;
        if range.start > range.end || range.end > payload_len {
            return Err(StreamedResourcePlanError::InvalidPayloadRange {
                start: range.start,
                end: range.end,
                payload_len,
            });
        }
        if !range.is_empty()
            && matches!(payload.provenance(), ArtifactPayloadProvenance::Generated)
            && (range.start != 0 || range.end != payload_len)
        {
            return Err(StreamedResourcePlanError::PartialGeneratedPayload {
                start: range.start,
                end: range.end,
                payload_len,
            });
        }
        let length = checked_size_usize(range.len())?;
        Ok(Self {
            payload: ExtentPayload::ArtifactRange { payload, range },
            alignment,
            length,
        })
    }

    #[must_use]
    pub const fn alignment(&self) -> u32 {
        self.alignment
    }

    #[must_use]
    pub const fn len(&self) -> u32 {
        self.length
    }

    #[must_use]
    pub const fn is_empty(&self) -> bool {
        self.length == 0
    }

    pub(crate) fn payload_digest(&self) -> DigestV1 {
        match &self.payload {
            ExtentPayload::Generated(bytes) => DigestV1::hash_bytes(bytes),
            ExtentPayload::Artifact(payload) => payload
                .digest()
                .unwrap_or_else(|| DigestV1::hash_bytes(payload.bytes())),
            ExtentPayload::ArtifactRange { payload, range } => {
                if range.start == 0 && range.end == payload.bytes().len() {
                    payload
                        .digest()
                        .unwrap_or_else(|| DigestV1::hash_bytes(payload.bytes()))
                } else {
                    DigestV1::hash_bytes(&payload.bytes()[range.clone()])
                }
            }
        }
    }

    pub(super) fn payload(&self) -> &ExtentPayload<'payload> {
        &self.payload
    }
}

/// A validated, deterministic allocation plan for one sidecar artifact.
///
/// The plan stores only a borrowed extent slice.  It therefore does not introduce an
/// unaccounted metadata allocation; the retained extent proof is charged by `ArtifactBatch` when
/// the plan is prepared.
#[derive(Debug, Clone, Copy)]
pub struct StreamedResourcePlan<'extent, 'payload> {
    flags: StreamedResourceFlags,
    extents: &'extent [StreamedResourceExtent<'payload>],
    length: u64,
}

impl<'extent, 'payload> StreamedResourcePlan<'extent, 'payload> {
    pub fn new(
        flags: StreamedResourceFlags,
        extents: &'extent [StreamedResourceExtent<'payload>],
    ) -> Result<Self, StreamedResourcePlanError> {
        let mut layout = StreamedResourceLayout::default();
        for extent in extents {
            layout.push(extent)?;
        }
        Ok(Self {
            flags,
            extents,
            length: layout.length(),
        })
    }

    #[must_use]
    pub const fn flags(self) -> StreamedResourceFlags {
        self.flags
    }

    #[must_use]
    pub const fn len(self) -> u64 {
        self.length
    }

    #[must_use]
    pub const fn is_empty(self) -> bool {
        self.length == 0
    }

    #[must_use]
    pub const fn extent_count(self) -> usize {
        self.extents.len()
    }

    #[must_use]
    pub fn extents(self) -> &'extent [StreamedResourceExtent<'payload>] {
        self.extents
    }

    #[must_use]
    pub fn allocations(self) -> StreamedResourceAllocationIter<'extent, 'payload> {
        StreamedResourceAllocationIter {
            extents: self.extents.iter(),
            layout: StreamedResourceLayout::default(),
        }
    }
}

/// Incrementally plans one deterministic streamed-resource sidecar.
///
/// Each successful [`Self::push`] charges the caller-owned load budget for one retained extent and
/// any new metadata backing before publishing the extent. The returned allocation is therefore
/// available to the mutation operation that introduced the bytes, while a failed push leaves the
/// planner unchanged. [`Self::finish`] borrows the retained extents without another allocation.
#[derive(Debug)]
#[must_use = "the planner must be finished or its allocations are discarded"]
pub struct StreamedResourcePlanner<'payload> {
    flags: StreamedResourceFlags,
    extents: Vec<StreamedResourceExtent<'payload>>,
    layout: StreamedResourceLayout,
}

impl<'payload> StreamedResourcePlanner<'payload> {
    pub const fn new(flags: StreamedResourceFlags) -> Self {
        Self {
            flags,
            extents: Vec::new(),
            layout: StreamedResourceLayout::new(),
        }
    }

    /// Appends one extent and returns its final placement immediately.
    ///
    /// Layout validation, count accounting, byte accounting, and allocation are completed before
    /// the planner advances. The caller can consequently attach any failure to the operation that
    /// supplied `extent` without rolling back earlier extents.
    pub fn push(
        &mut self,
        extent: StreamedResourceExtent<'payload>,
        budget: &mut AssetLoadBudget,
    ) -> Result<StreamedResourceAllocation, StreamedResourcePlannerError> {
        let (next_layout, allocation) = self.layout.next(&extent)?;
        reserve_extent_slot(&mut self.extents, budget)?;
        self.extents.push(extent);
        self.layout = next_layout;
        Ok(allocation)
    }

    #[must_use]
    pub const fn flags(&self) -> StreamedResourceFlags {
        self.flags
    }

    #[must_use]
    pub const fn len(&self) -> u64 {
        self.layout.length()
    }

    #[must_use]
    pub const fn is_empty(&self) -> bool {
        self.layout.length() == 0
    }

    #[must_use]
    pub const fn extent_count(&self) -> usize {
        self.extents.len()
    }

    /// Returns the completed borrowed plan without copying extent metadata.
    #[must_use]
    pub fn finish(&self) -> StreamedResourcePlan<'_, 'payload> {
        StreamedResourcePlan {
            flags: self.flags,
            extents: &self.extents,
            length: self.layout.length(),
        }
    }
}

/// Deterministic placement of one resource extent.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct StreamedResourceAllocation {
    ordinal: usize,
    offset: u64,
    size: u32,
    alignment: u32,
    padding_before: u64,
}

impl StreamedResourceAllocation {
    #[must_use]
    pub const fn ordinal(self) -> usize {
        self.ordinal
    }

    #[must_use]
    pub const fn offset(self) -> u64 {
        self.offset
    }

    #[must_use]
    pub const fn size(self) -> u32 {
        self.size
    }

    #[must_use]
    pub const fn alignment(self) -> u32 {
        self.alignment
    }

    #[must_use]
    pub const fn padding_before(self) -> u64 {
        self.padding_before
    }

    #[must_use]
    pub const fn end(self) -> u64 {
        self.offset.saturating_add(self.size as u64)
    }
}

/// Iterator over a validated plan's placements.
pub struct StreamedResourceAllocationIter<'extent, 'payload> {
    extents: std::slice::Iter<'extent, StreamedResourceExtent<'payload>>,
    layout: StreamedResourceLayout,
}

impl Iterator for StreamedResourceAllocationIter<'_, '_> {
    type Item = StreamedResourceAllocation;

    fn next(&mut self) -> Option<Self::Item> {
        let extent = self.extents.next()?;
        // Every public plan constructor validates this exact transition. Returning `None` keeps
        // the iterator total if an internal constructor ever violates that invariant.
        let (next_layout, allocation) = self.layout.next(extent).ok()?;
        self.layout = next_layout;
        Some(allocation)
    }

    fn size_hint(&self) -> (usize, Option<usize>) {
        let length = self.extents.len();
        (length, Some(length))
    }
}

impl ExactSizeIterator for StreamedResourceAllocationIter<'_, '_> {}
impl FusedIterator for StreamedResourceAllocationIter<'_, '_> {}

#[derive(Debug, Error, PartialEq, Eq)]
pub enum StreamedResourcePlanError {
    #[error("streamed-resource alignment {alignment} must be a nonzero power of two")]
    InvalidAlignment { alignment: u32 },
    #[error("streamed-resource payload length {length} does not fit the Unity u32 size field")]
    PayloadTooLarge { length: u64 },
    #[error("streamed-resource payload length {length} does not fit the platform index domain")]
    PayloadLengthOverflow { length: u64 },
    #[error("streamed-resource payload range {start}..{end} exceeds payload length {payload_len}")]
    InvalidPayloadRange {
        start: usize,
        end: usize,
        payload_len: usize,
    },
    #[error(
        "generated streamed-resource payload range {start}..{end} must retain the complete {payload_len}-byte allocation"
    )]
    PartialGeneratedPayload {
        start: usize,
        end: usize,
        payload_len: usize,
    },
    #[error("streamed-resource layout length overflow at extent {ordinal}")]
    LengthOverflow { ordinal: usize },
    #[error("streamed-resource extent count cannot be represented after extent {ordinal}")]
    ExtentCountOverflow { ordinal: usize },
}

/// Typed failure from an incremental streamed-resource planner operation.
#[derive(Debug, Error)]
pub enum StreamedResourcePlannerError {
    #[error(transparent)]
    Plan(#[from] StreamedResourcePlanError),
    #[error("failed to reserve {requested} streamed-resource extent slots: {source}")]
    Allocation {
        requested: usize,
        #[source]
        source: TryReserveError,
    },
    #[error(transparent)]
    AllocationSize(#[from] AllocationSizeError),
    #[error(transparent)]
    Budget(#[from] BudgetError),
}

#[derive(Debug, Clone, Copy, Default)]
struct StreamedResourceLayout {
    cursor: u64,
    extent_count: usize,
}

impl StreamedResourceLayout {
    const fn new() -> Self {
        Self {
            cursor: 0,
            extent_count: 0,
        }
    }

    const fn length(self) -> u64 {
        self.cursor
    }

    fn push(
        &mut self,
        extent: &StreamedResourceExtent<'_>,
    ) -> Result<StreamedResourceAllocation, StreamedResourcePlanError> {
        let (next, allocation) = self.next(extent)?;
        *self = next;
        Ok(allocation)
    }

    fn next(
        self,
        extent: &StreamedResourceExtent<'_>,
    ) -> Result<(Self, StreamedResourceAllocation), StreamedResourcePlanError> {
        // Constructors validate this already. Recheck it here so the layout remains robust if
        // more constructors are added in the future.
        validate_alignment(extent.alignment)?;
        let ordinal = self.extent_count;
        let offset = if ordinal == 0 {
            0
        } else {
            align_up(self.cursor, extent.alignment)
                .ok_or(StreamedResourcePlanError::LengthOverflow { ordinal })?
        };
        let cursor = offset
            .checked_add(u64::from(extent.length))
            .ok_or(StreamedResourcePlanError::LengthOverflow { ordinal })?;
        let extent_count = ordinal
            .checked_add(1)
            .ok_or(StreamedResourcePlanError::ExtentCountOverflow { ordinal })?;
        let padding_before = offset
            .checked_sub(self.cursor)
            .ok_or(StreamedResourcePlanError::LengthOverflow { ordinal })?;
        let allocation = StreamedResourceAllocation {
            ordinal,
            offset,
            size: extent.length,
            alignment: extent.alignment,
            padding_before,
        };
        Ok((
            Self {
                cursor,
                extent_count,
            },
            allocation,
        ))
    }
}

fn reserve_extent_slot(
    extents: &mut Vec<StreamedResourceExtent<'_>>,
    budget: &mut AssetLoadBudget,
) -> Result<(), StreamedResourcePlannerError> {
    budget.check_entries(1)?;
    if extents.len() < extents.capacity() {
        budget.consume_entries(1)?;
        return Ok(());
    }

    let ordinal = extents.len();
    let required = ordinal
        .checked_add(1)
        .ok_or(StreamedResourcePlanError::ExtentCountOverflow { ordinal })?;
    let target_capacity = match extents.capacity().checked_mul(2) {
        Some(doubled) => doubled.max(required).max(4),
        None => required,
    };
    let planned_bytes = vec_allocation_bytes::<StreamedResourceExtent<'_>>(target_capacity)?;
    budget.check_bytes(planned_bytes)?;

    // Stage the replacement backing so allocation or supplemental-budget failure leaves the
    // planner and its previously returned allocations unchanged.
    let mut staged = Vec::new();
    staged
        .try_reserve_exact(target_capacity)
        .map_err(|source| StreamedResourcePlannerError::Allocation {
            requested: target_capacity,
            source,
        })?;
    let actual_bytes = vec_allocation_bytes::<StreamedResourceExtent<'_>>(staged.capacity())?;
    budget.check_bytes(actual_bytes)?;
    budget.consume_entries(1)?;
    budget.consume_bytes(actual_bytes)?;

    staged.append(extents);
    *extents = staged;
    Ok(())
}

fn checked_size_usize(length: usize) -> Result<u32, StreamedResourcePlanError> {
    u32::try_from(length).map_err(|_| StreamedResourcePlanError::PayloadTooLarge {
        length: u64::try_from(length).unwrap_or(u64::MAX),
    })
}

fn checked_size_u64(length: u64) -> Result<u32, StreamedResourcePlanError> {
    u32::try_from(length).map_err(|_| StreamedResourcePlanError::PayloadTooLarge { length })
}

fn validate_alignment(alignment: u32) -> Result<(), StreamedResourcePlanError> {
    if alignment == 0 || !alignment.is_power_of_two() {
        return Err(StreamedResourcePlanError::InvalidAlignment { alignment });
    }
    Ok(())
}

fn align_up(value: u64, alignment: u32) -> Option<u64> {
    let mask = u64::from(alignment) - 1;
    value.checked_add(mask).map(|value| value & !mask)
}
