use std::collections::TryReserveError;
use std::iter::FusedIterator;
use std::ops::Range;

use thiserror::Error;
use unity_asset_core::{
    AllocationSizeError, AssetLoadBudget, BudgetError, DigestBuildError, DigestV1, DigestV1Builder,
    vec_allocation_bytes,
};

use crate::artifact::{ArtifactPayload, ArtifactPayloadProvenance};

/// Flags retained with a streamed-resource artifact for its containing format node.
///
/// The bit layout belongs to the enclosing Unity container (AssetBundle or WebFile), so this
/// module deliberately treats the value as opaque while still avoiding an unlabelled `u32` in
/// resource planning APIs.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash)]
pub struct StreamedResourceFlags(u32);

impl StreamedResourceFlags {
    #[must_use]
    pub const fn new(bits: u32) -> Self {
        Self(bits)
    }

    #[must_use]
    pub const fn bits(self) -> u32 {
        self.0
    }
}

impl From<u32> for StreamedResourceFlags {
    fn from(bits: u32) -> Self {
        Self::new(bits)
    }
}

/// One borrowed payload to place in a streamed-resource sidecar.
#[derive(Debug, Clone)]
pub(super) enum ExtentPayload<'payload> {
    Generated(&'payload [u8]),
    Artifact(&'payload ArtifactPayload),
    ArtifactRange {
        payload: &'payload ArtifactPayload,
        range: Range<usize>,
    },
}

/// One resource extent and its required alignment.
///
/// Extents are borrowed intentionally.  The caller (usually the workspace mutation overlay)
/// remains the owner of input bytes; the artifact transaction only retains the exact source ranges
/// or generated chunks that are reachable from a committed output.
#[derive(Debug, Clone)]
pub struct StreamedResourceExtent<'payload> {
    payload: ExtentPayload<'payload>,
    payload_digest: DigestV1,
    alignment: u32,
    length: u32,
}

impl<'payload> StreamedResourceExtent<'payload> {
    /// Creates an extent backed by newly generated bytes.
    pub fn generated(
        bytes: &'payload [u8],
        alignment: u32,
    ) -> Result<Self, StreamedResourcePlanError> {
        validate_alignment(alignment)?;
        let length = checked_size_usize(bytes.len())?;
        Ok(Self {
            payload: ExtentPayload::Generated(bytes),
            payload_digest: DigestV1::hash_bytes(bytes),
            alignment,
            length,
        })
    }

    /// Creates an extent backed by a complete immutable artifact payload.
    pub fn artifact_payload(
        payload: &'payload ArtifactPayload,
        alignment: u32,
    ) -> Result<Self, StreamedResourcePlanError> {
        validate_alignment(alignment)?;
        let length = checked_size_u64(payload.len())?;
        Ok(Self {
            payload: ExtentPayload::Artifact(payload),
            payload_digest: payload
                .digest()
                .unwrap_or_else(|| DigestV1::hash_bytes(payload.bytes())),
            alignment,
            length,
        })
    }

    /// Creates an extent backed by a zero-copy range of an immutable artifact payload.
    pub fn artifact_payload_range(
        payload: &'payload ArtifactPayload,
        range: Range<usize>,
        alignment: u32,
    ) -> Result<Self, StreamedResourcePlanError> {
        validate_alignment(alignment)?;
        let payload_len = usize::try_from(payload.len()).map_err(|_| {
            StreamedResourcePlanError::PayloadLengthOverflow {
                length: payload.len(),
            }
        })?;
        if range.start > range.end || range.end > payload_len {
            return Err(StreamedResourcePlanError::InvalidPayloadRange {
                start: range.start,
                end: range.end,
                payload_len,
            });
        }
        if !range.is_empty()
            && matches!(payload.provenance(), ArtifactPayloadProvenance::Generated)
            && (range.start != 0 || range.end != payload_len)
        {
            return Err(StreamedResourcePlanError::PartialGeneratedPayload {
                start: range.start,
                end: range.end,
                payload_len,
            });
        }
        let length = checked_size_usize(range.len())?;
        let payload_digest = if range.start == 0 && range.end == payload.bytes().len() {
            payload
                .digest()
                .unwrap_or_else(|| DigestV1::hash_bytes(payload.bytes()))
        } else {
            DigestV1::hash_bytes(&payload.bytes()[range.clone()])
        };
        Ok(Self {
            payload: ExtentPayload::ArtifactRange { payload, range },
            payload_digest,
            alignment,
            length,
        })
    }

    #[must_use]
    pub const fn alignment(&self) -> u32 {
        self.alignment
    }

    #[must_use]
    pub const fn len(&self) -> u32 {
        self.length
    }

    #[must_use]
    pub const fn is_empty(&self) -> bool {
        self.length == 0
    }

    pub(crate) const fn payload_digest(&self) -> DigestV1 {
        self.payload_digest
    }

    pub(super) fn payload(&self) -> &ExtentPayload<'payload> {
        &self.payload
    }

    fn payload_bytes(&self) -> &[u8] {
        match &self.payload {
            ExtentPayload::Generated(bytes) => bytes,
            ExtentPayload::Artifact(payload) => payload.bytes(),
            ExtentPayload::ArtifactRange { payload, range } => &payload.bytes()[range.clone()],
        }
    }
}

#[derive(Debug)]
enum StreamedResourceExtents<'extent, 'payload> {
    Borrowed(&'extent [StreamedResourceExtent<'payload>]),
    Owned(Vec<StreamedResourceExtent<'payload>>),
}

impl<'payload> StreamedResourceExtents<'_, 'payload> {
    const fn len(&self) -> usize {
        match self {
            Self::Borrowed(extents) => extents.len(),
            Self::Owned(extents) => extents.len(),
        }
    }

    fn as_slice(&self) -> &[StreamedResourceExtent<'payload>] {
        match self {
            Self::Borrowed(extents) => extents,
            Self::Owned(extents) => extents,
        }
    }
}

/// A validated, deterministic allocation plan for one sidecar artifact.
///
/// A plan built from a complete slice borrows that slice without allocating. A plan finished from
/// [`StreamedResourcePlanner`] takes ownership of the planner's already-budgeted metadata. The
/// retained artifact proof is charged separately by `ArtifactBatch` when the plan is prepared.
#[derive(Debug)]
pub struct StreamedResourcePlan<'extent, 'payload> {
    flags: StreamedResourceFlags,
    extents: StreamedResourceExtents<'extent, 'payload>,
    length: u64,
}

impl<'extent, 'payload> StreamedResourcePlan<'extent, 'payload> {
    pub fn new(
        flags: StreamedResourceFlags,
        extents: &'extent [StreamedResourceExtent<'payload>],
    ) -> Result<Self, StreamedResourcePlanError> {
        let mut layout = StreamedResourceLayout::default();
        for extent in extents {
            layout.push(extent)?;
        }
        Ok(Self {
            flags,
            extents: StreamedResourceExtents::Borrowed(extents),
            length: layout.length(),
        })
    }

    #[must_use]
    pub const fn flags(&self) -> StreamedResourceFlags {
        self.flags
    }

    #[must_use]
    pub const fn len(&self) -> u64 {
        self.length
    }

    #[must_use]
    pub const fn is_empty(&self) -> bool {
        self.length == 0
    }

    #[must_use]
    pub const fn extent_count(&self) -> usize {
        self.extents.len()
    }

    #[must_use]
    pub fn extents(&self) -> &[StreamedResourceExtent<'payload>] {
        self.extents.as_slice()
    }

    #[must_use]
    pub fn allocations(&self) -> StreamedResourceAllocationIter<'_, 'payload> {
        StreamedResourceAllocationIter {
            extents: self.extents.as_slice().iter(),
            layout: StreamedResourceLayout::default(),
        }
    }

    /// Computes the digest of the exact sidecar bytes, including deterministic zero padding.
    ///
    /// This operation streams borrowed payloads directly into the digest and neither allocates nor
    /// consumes an [`AssetLoadBudget`]. Flags are container metadata and therefore do not affect
    /// the content identity.
    pub fn content_digest(&self) -> Result<DigestV1, StreamedResourcePlanError> {
        let mut digest = DigestV1Builder::new(self.length);
        for (extent, allocation) in self.extents().iter().zip(self.allocations()) {
            update_zero_padding(&mut digest, allocation.padding_before())?;
            digest.update(extent.payload_bytes())?;
        }
        Ok(digest.finalize()?)
    }
}

/// An allocation preview bound to one planner state and one exact payload.
///
/// The token is intentionally opaque. It can only be produced by [`StreamedResourcePlanner`] and
/// must be consumed by [`StreamedResourcePlanner::push_previewed`] before any other extent advances
/// that planner.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct StreamedResourcePreview {
    state: StreamedResourcePlannerState,
    allocation: StreamedResourceAllocation,
    payload_digest: DigestV1,
}

impl StreamedResourcePreview {
    #[must_use]
    pub const fn allocation(self) -> StreamedResourceAllocation {
        self.allocation
    }

    #[must_use]
    pub const fn payload_digest(self) -> DigestV1 {
        self.payload_digest
    }
}

/// Incrementally plans one deterministic streamed-resource sidecar.
///
/// Each successful [`Self::push_previewed`] charges the caller-owned load budget for one retained
/// extent and any new metadata backing before publishing the extent. The previewed allocation is
/// therefore available to the mutation operation that introduced the bytes, while a failed push
/// leaves the planner unchanged. [`Self::finish`] consumes the planner without another allocation.
#[derive(Debug)]
#[must_use = "the planner must be finished or its allocations are discarded"]
pub struct StreamedResourcePlanner<'payload> {
    flags: StreamedResourceFlags,
    extents: Vec<StreamedResourceExtent<'payload>>,
    layout: StreamedResourceLayout,
}

impl<'payload> StreamedResourcePlanner<'payload> {
    pub const fn new(flags: StreamedResourceFlags) -> Self {
        Self {
            flags,
            extents: Vec::new(),
            layout: StreamedResourceLayout::new(),
        }
    }

    /// Computes the next exact placement without changing state or consuming budget.
    ///
    /// The returned token remains valid only while this planner has not accepted another extent.
    /// Its payload digest prevents a same-shaped but different payload from being appended after a
    /// caller has used the previewed offset and size in a read-after-write mutation.
    pub fn preview_next(
        &self,
        extent: &StreamedResourceExtent<'_>,
    ) -> Result<StreamedResourcePreview, StreamedResourcePlannerError> {
        let (_, allocation) = self.layout.next(extent)?;
        Ok(StreamedResourcePreview {
            state: self.state(),
            allocation,
            payload_digest: extent.payload_digest(),
        })
    }

    /// Appends the exact extent previously accepted by [`Self::preview_next`].
    ///
    /// Preview validation, layout validation, count accounting, byte accounting, and allocation
    /// are completed before the planner advances. Any failure leaves both planner and budget
    /// unchanged.
    pub fn push_previewed(
        &mut self,
        preview: StreamedResourcePreview,
        extent: StreamedResourceExtent<'payload>,
        budget: &mut AssetLoadBudget,
    ) -> Result<StreamedResourceAllocation, StreamedResourcePlannerError> {
        let actual_state = self.state();
        if preview.state != actual_state {
            return Err(StreamedResourcePlannerError::StalePreview {
                expected_ordinal: preview.state.extent_count,
                expected_length: preview.state.length,
                actual_ordinal: actual_state.extent_count,
                actual_length: actual_state.length,
            });
        }
        if preview.allocation.size != extent.length
            || preview.allocation.alignment != extent.alignment
        {
            return Err(StreamedResourcePlannerError::PreviewShapeMismatch {
                expected_size: preview.allocation.size,
                expected_alignment: preview.allocation.alignment,
                actual_size: extent.length,
                actual_alignment: extent.alignment,
            });
        }
        if preview.payload_digest != extent.payload_digest() {
            return Err(StreamedResourcePlannerError::PreviewPayloadMismatch {
                expected: preview.payload_digest,
                actual: extent.payload_digest(),
            });
        }
        let (next_layout, allocation) = self.layout.next(&extent)?;
        debug_assert_eq!(allocation, preview.allocation);
        reserve_extent_slot(&mut self.extents, budget)?;
        self.extents.push(extent);
        self.layout = next_layout;
        Ok(allocation)
    }

    #[must_use]
    pub const fn flags(&self) -> StreamedResourceFlags {
        self.flags
    }

    #[must_use]
    pub const fn len(&self) -> u64 {
        self.layout.length()
    }

    #[must_use]
    pub const fn is_empty(&self) -> bool {
        self.layout.length() == 0
    }

    #[must_use]
    pub const fn extent_count(&self) -> usize {
        self.extents.len()
    }

    /// Consumes the planner and seals its already-budgeted metadata into a completed plan.
    ///
    /// Consuming `self` makes post-seal preview or append attempts unrepresentable. No extent
    /// metadata is copied or allocated by this transition.
    #[must_use]
    pub fn finish(self) -> StreamedResourcePlan<'payload, 'payload> {
        StreamedResourcePlan {
            flags: self.flags,
            extents: StreamedResourceExtents::Owned(self.extents),
            length: self.layout.length(),
        }
    }

    const fn state(&self) -> StreamedResourcePlannerState {
        StreamedResourcePlannerState {
            extent_count: self.layout.extent_count,
            length: self.layout.length(),
        }
    }
}

/// Deterministic placement of one resource extent.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct StreamedResourceAllocation {
    ordinal: usize,
    offset: u64,
    size: u32,
    alignment: u32,
    padding_before: u64,
}

impl StreamedResourceAllocation {
    #[must_use]
    pub const fn ordinal(self) -> usize {
        self.ordinal
    }

    #[must_use]
    pub const fn offset(self) -> u64 {
        self.offset
    }

    #[must_use]
    pub const fn size(self) -> u32 {
        self.size
    }

    #[must_use]
    pub const fn alignment(self) -> u32 {
        self.alignment
    }

    #[must_use]
    pub const fn padding_before(self) -> u64 {
        self.padding_before
    }

    #[must_use]
    pub const fn end(self) -> u64 {
        self.offset.saturating_add(self.size as u64)
    }
}

/// Iterator over a validated plan's placements.
pub struct StreamedResourceAllocationIter<'extent, 'payload> {
    extents: std::slice::Iter<'extent, StreamedResourceExtent<'payload>>,
    layout: StreamedResourceLayout,
}

impl Iterator for StreamedResourceAllocationIter<'_, '_> {
    type Item = StreamedResourceAllocation;

    fn next(&mut self) -> Option<Self::Item> {
        let extent = self.extents.next()?;
        // Every public plan constructor validates this exact transition. Returning `None` keeps
        // the iterator total if an internal constructor ever violates that invariant.
        let (next_layout, allocation) = self.layout.next(extent).ok()?;
        self.layout = next_layout;
        Some(allocation)
    }

    fn size_hint(&self) -> (usize, Option<usize>) {
        let length = self.extents.len();
        (length, Some(length))
    }
}

impl ExactSizeIterator for StreamedResourceAllocationIter<'_, '_> {}
impl FusedIterator for StreamedResourceAllocationIter<'_, '_> {}

#[derive(Debug, Error, PartialEq, Eq)]
pub enum StreamedResourcePlanError {
    #[error("streamed-resource alignment {alignment} must be a nonzero power of two")]
    InvalidAlignment { alignment: u32 },
    #[error("streamed-resource payload length {length} does not fit the Unity u32 size field")]
    PayloadTooLarge { length: u64 },
    #[error("streamed-resource payload length {length} does not fit the platform index domain")]
    PayloadLengthOverflow { length: u64 },
    #[error("streamed-resource payload range {start}..{end} exceeds payload length {payload_len}")]
    InvalidPayloadRange {
        start: usize,
        end: usize,
        payload_len: usize,
    },
    #[error(
        "generated streamed-resource payload range {start}..{end} must retain the complete {payload_len}-byte allocation"
    )]
    PartialGeneratedPayload {
        start: usize,
        end: usize,
        payload_len: usize,
    },
    #[error("streamed-resource layout length overflow at extent {ordinal}")]
    LengthOverflow { ordinal: usize },
    #[error("streamed-resource extent count cannot be represented after extent {ordinal}")]
    ExtentCountOverflow { ordinal: usize },
    #[error("failed to digest exact streamed-resource content: {0}")]
    Digest(#[from] DigestBuildError),
}

/// Typed failure from an incremental streamed-resource planner operation.
#[derive(Debug, Error)]
pub enum StreamedResourcePlannerError {
    #[error(transparent)]
    Plan(#[from] StreamedResourcePlanError),
    #[error("failed to reserve {requested} streamed-resource extent slots: {source}")]
    Allocation {
        requested: usize,
        #[source]
        source: TryReserveError,
    },
    #[error(transparent)]
    AllocationSize(#[from] AllocationSizeError),
    #[error(transparent)]
    Budget(#[from] BudgetError),
    #[error(
        "streamed-resource preview for extent {expected_ordinal} at length {expected_length} is stale; planner is at extent {actual_ordinal} and length {actual_length}"
    )]
    StalePreview {
        expected_ordinal: usize,
        expected_length: u64,
        actual_ordinal: usize,
        actual_length: u64,
    },
    #[error(
        "streamed-resource preview expected size {expected_size} and alignment {expected_alignment}, but push supplied size {actual_size} and alignment {actual_alignment}"
    )]
    PreviewShapeMismatch {
        expected_size: u32,
        expected_alignment: u32,
        actual_size: u32,
        actual_alignment: u32,
    },
    #[error(
        "streamed-resource preview expected payload digest {expected}, but push supplied {actual}"
    )]
    PreviewPayloadMismatch {
        expected: DigestV1,
        actual: DigestV1,
    },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct StreamedResourcePlannerState {
    extent_count: usize,
    length: u64,
}

#[derive(Debug, Clone, Copy, Default)]
struct StreamedResourceLayout {
    cursor: u64,
    extent_count: usize,
}

impl StreamedResourceLayout {
    const fn new() -> Self {
        Self {
            cursor: 0,
            extent_count: 0,
        }
    }

    const fn length(self) -> u64 {
        self.cursor
    }

    fn push(
        &mut self,
        extent: &StreamedResourceExtent<'_>,
    ) -> Result<StreamedResourceAllocation, StreamedResourcePlanError> {
        let (next, allocation) = self.next(extent)?;
        *self = next;
        Ok(allocation)
    }

    fn next(
        self,
        extent: &StreamedResourceExtent<'_>,
    ) -> Result<(Self, StreamedResourceAllocation), StreamedResourcePlanError> {
        // Constructors validate this already. Recheck it here so the layout remains robust if
        // more constructors are added in the future.
        validate_alignment(extent.alignment)?;
        let ordinal = self.extent_count;
        let offset = if ordinal == 0 {
            0
        } else {
            align_up(self.cursor, extent.alignment)
                .ok_or(StreamedResourcePlanError::LengthOverflow { ordinal })?
        };
        let cursor = offset
            .checked_add(u64::from(extent.length))
            .ok_or(StreamedResourcePlanError::LengthOverflow { ordinal })?;
        let extent_count = ordinal
            .checked_add(1)
            .ok_or(StreamedResourcePlanError::ExtentCountOverflow { ordinal })?;
        let padding_before = offset
            .checked_sub(self.cursor)
            .ok_or(StreamedResourcePlanError::LengthOverflow { ordinal })?;
        let allocation = StreamedResourceAllocation {
            ordinal,
            offset,
            size: extent.length,
            alignment: extent.alignment,
            padding_before,
        };
        Ok((
            Self {
                cursor,
                extent_count,
            },
            allocation,
        ))
    }
}

fn reserve_extent_slot(
    extents: &mut Vec<StreamedResourceExtent<'_>>,
    budget: &mut AssetLoadBudget,
) -> Result<(), StreamedResourcePlannerError> {
    budget.check_entries(1)?;
    if extents.len() < extents.capacity() {
        budget.consume_entries(1)?;
        return Ok(());
    }

    let ordinal = extents.len();
    let required = ordinal
        .checked_add(1)
        .ok_or(StreamedResourcePlanError::ExtentCountOverflow { ordinal })?;
    let target_capacity = match extents.capacity().checked_mul(2) {
        Some(doubled) => doubled.max(required).max(4),
        None => required,
    };
    let planned_bytes = vec_allocation_bytes::<StreamedResourceExtent<'_>>(target_capacity)?;
    budget.check_bytes(planned_bytes)?;

    // Stage the replacement backing so allocation or supplemental-budget failure leaves the
    // planner and its previously returned allocations unchanged.
    let mut staged = Vec::new();
    staged
        .try_reserve_exact(target_capacity)
        .map_err(|source| StreamedResourcePlannerError::Allocation {
            requested: target_capacity,
            source,
        })?;
    let actual_bytes = vec_allocation_bytes::<StreamedResourceExtent<'_>>(staged.capacity())?;
    budget.check_bytes(actual_bytes)?;
    budget.consume_entries(1)?;
    budget.consume_bytes(actual_bytes)?;

    staged.append(extents);
    *extents = staged;
    Ok(())
}

fn checked_size_usize(length: usize) -> Result<u32, StreamedResourcePlanError> {
    u32::try_from(length).map_err(|_| StreamedResourcePlanError::PayloadTooLarge {
        length: u64::try_from(length).unwrap_or(u64::MAX),
    })
}

fn checked_size_u64(length: u64) -> Result<u32, StreamedResourcePlanError> {
    u32::try_from(length).map_err(|_| StreamedResourcePlanError::PayloadTooLarge { length })
}

fn validate_alignment(alignment: u32) -> Result<(), StreamedResourcePlanError> {
    if alignment == 0 || !alignment.is_power_of_two() {
        return Err(StreamedResourcePlanError::InvalidAlignment { alignment });
    }
    Ok(())
}

fn align_up(value: u64, alignment: u32) -> Option<u64> {
    let mask = u64::from(alignment) - 1;
    value.checked_add(mask).map(|value| value & !mask)
}

fn update_zero_padding(
    digest: &mut DigestV1Builder,
    mut remaining: u64,
) -> Result<(), DigestBuildError> {
    const ZEROES: [u8; 4 * 1024] = [0; 4 * 1024];

    while remaining != 0 {
        let chunk_length = remaining.min(ZEROES.len() as u64) as usize;
        digest.update(&ZEROES[..chunk_length])?;
        remaining -= chunk_length as u64;
    }
    Ok(())
}

#[cfg(test)]
mod internal_tests {
    use super::*;

    #[test]
    fn layout_rejects_alignment_overflow() {
        let layout = StreamedResourceLayout {
            cursor: u64::MAX - 1,
            extent_count: 7,
        };
        let extent = StreamedResourceExtent::generated(b"x", 4).unwrap();

        assert!(matches!(
            layout.next(&extent),
            Err(StreamedResourcePlanError::LengthOverflow { ordinal: 7 })
        ));
        assert_eq!(layout.length(), u64::MAX - 1);
    }

    #[test]
    fn layout_rejects_extent_end_overflow() {
        let layout = StreamedResourceLayout {
            cursor: u64::MAX - 1,
            extent_count: 3,
        };
        let extent = StreamedResourceExtent::generated(b"xx", 1).unwrap();

        assert!(matches!(
            layout.next(&extent),
            Err(StreamedResourcePlanError::LengthOverflow { ordinal: 3 })
        ));
        assert_eq!(layout.length(), u64::MAX - 1);
    }

    #[test]
    fn layout_rejects_extent_count_overflow() {
        let layout = StreamedResourceLayout {
            cursor: 0,
            extent_count: usize::MAX,
        };
        let extent = StreamedResourceExtent::generated(b"", 1).unwrap();

        assert!(matches!(
            layout.next(&extent),
            Err(StreamedResourcePlanError::ExtentCountOverflow {
                ordinal: usize::MAX
            })
        ));
        assert_eq!(layout.length(), 0);
    }
}
