#!/usr/bin/env python3
"""Generate independent SerializedFile wire fixtures used by Rust tests.

This generator intentionally does not import UnityPy or this repository's writer.
Its field order is frozen from the cross-checked format references recorded in
the generated manifest. Tests consume the generated bytes but never run this
script, so parser and writer changes cannot silently update their own oracle.
"""

from __future__ import annotations

import hashlib
import json
import struct
from dataclasses import dataclass
from pathlib import Path


VERSIONS = (2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22)
RESERVED = bytes((0xA1, 0xB2, 0xC3))
TYPE_HASH = bytes(range(0x20, 0x30))
REF_SCRIPT_ID = bytes(range(0x40, 0x50))
REF_TYPE_HASH = bytes(range(0x60, 0x70))
LEGACY_SCRIPT_ID = bytes(range(0x80, 0x90))


@dataclass
class WireWriter:
    big_endian: bool

    def __post_init__(self) -> None:
        self.data = bytearray()

    @property
    def prefix(self) -> str:
        return ">" if self.big_endian else "<"

    def raw(self, value: bytes) -> None:
        self.data.extend(value)

    def u8(self, value: int) -> None:
        self.data.extend(struct.pack("B", value))

    def i16(self, value: int) -> None:
        self.data.extend(struct.pack(f"{self.prefix}h", value))

    def u16(self, value: int) -> None:
        self.data.extend(struct.pack(f"{self.prefix}H", value))

    def i32(self, value: int) -> None:
        self.data.extend(struct.pack(f"{self.prefix}i", value))

    def u32(self, value: int) -> None:
        self.data.extend(struct.pack(f"{self.prefix}I", value))

    def i64(self, value: int) -> None:
        self.data.extend(struct.pack(f"{self.prefix}q", value))

    def u64(self, value: int) -> None:
        self.data.extend(struct.pack(f"{self.prefix}Q", value))

    def cstring(self, value: str) -> None:
        self.data.extend(value.encode("utf-8"))
        self.data.append(0)

    def align(self, alignment: int) -> None:
        padding = (-len(self.data)) % alignment
        self.data.extend(bytes(padding))


def uses_blob_type_tree(version: int) -> bool:
    return version == 10 or version >= 12


def mark(ranges: dict[str, dict[str, int]], name: str, offset: int, size: int) -> None:
    ranges[name] = {"metadata_offset": offset, "size": size}


def write_type_tree(
    writer: WireWriter,
    version: int,
    *,
    ref_type: bool,
    ranges: dict[str, dict[str, int]] | None = None,
) -> None:
    if not uses_blob_type_tree(version):
        writer.cstring("int")
        writer.cstring("m_Value")
        writer.i32(4)
        if version == 2:
            writer.i32(0x11223344)
        if version != 3:
            writer.i32(7)
        writer.i32(3)
        writer.i32(1)
        if version != 3:
            writer.i32(0x4000)
        if ranges is not None:
            mark(ranges, "legacy_child_count", len(writer.data), 4)
        writer.i32(0)
        return

    string_buffer = b"int\0m_Value\0"
    if ranges is not None:
        mark(ranges, "type_tree_node_count", len(writer.data), 4)
    writer.i32(1)
    if ranges is not None:
        mark(ranges, "type_tree_string_buffer_size", len(writer.data), 4)
    writer.i32(len(string_buffer))
    writer.u16(1)
    writer.u8(0)
    writer.u8(3)
    if ranges is not None:
        mark(ranges, "type_tree_type_string_offset", len(writer.data), 4)
    writer.u32(0)
    if ranges is not None:
        mark(ranges, "type_tree_name_string_offset", len(writer.data), 4)
    writer.u32(4)
    if ranges is not None:
        mark(ranges, "type_tree_node_byte_size", len(writer.data), 4)
    writer.i32(4)
    writer.i32(7)
    writer.i32(0x4000)
    if version >= 19:
        writer.u64(0x0102030405060708 if ref_type else 0x1112131415161718)
    if ranges is not None:
        mark(ranges, "type_tree_string_buffer", len(writer.data), len(string_buffer))
    writer.raw(string_buffer)


def write_serialized_type(
    writer: WireWriter,
    version: int,
    *,
    ref_type: bool = False,
    class_id_override: int | None = None,
    script_type_index_override: int | None = None,
    script_id_override: bytes | None = None,
    ranges: dict[str, dict[str, int]] | None = None,
) -> None:
    class_id = class_id_override if class_id_override is not None else (114 if ref_type else 28)
    if ranges is not None:
        mark(ranges, "serialized_type_class_id", len(writer.data), 4)
    writer.i32(class_id)
    if version >= 16:
        writer.u8(0)
    script_type_index = (
        script_type_index_override
        if script_type_index_override is not None
        else (2 if ref_type else -1)
    )
    if version >= 17:
        writer.i16(script_type_index)
    if version >= 13:
        has_script_id = (
            (ref_type and script_type_index >= 0)
            or (version < 16 and class_id < 0)
            or (version >= 16 and class_id == 114)
        )
        if has_script_id:
            script_id = script_id_override or (REF_SCRIPT_ID if ref_type else LEGACY_SCRIPT_ID)
            writer.raw(script_id)
        writer.raw(REF_TYPE_HASH if ref_type else TYPE_HASH)
    write_type_tree(writer, version, ref_type=ref_type, ranges=ranges)
    if version >= 21:
        if ref_type:
            writer.cstring("FixtureRef")
            writer.cstring("Fixture.Tests")
            writer.cstring("Fixture.Assembly")
        else:
            if ranges is not None:
                mark(ranges, "type_dependency_count", len(writer.data), 4)
            writer.i32(2)
            writer.i32(114)
            writer.i32(-7)


def write_external(writer: WireWriter, version: int) -> None:
    if version >= 6:
        writer.cstring("fixture-empty")
    if version >= 5:
        writer.raw(bytes(range(1, 17)))
        writer.i32(3)
    writer.cstring("archive:/fixture-dependency.assets")


def build_metadata(version: int, *, big_endian: bool) -> tuple[bytes, dict[str, object]]:
    writer = WireWriter(big_endian)
    ranges: dict[str, dict[str, int]] = {}
    if version >= 7:
        writer.cstring("5.5.0a1" if version == 16 else "2020.1.0f1")
    if version >= 8:
        writer.i32(13)
    if version >= 13:
        mark(ranges, "enable_type_tree", len(writer.data), 1)
        writer.u8(1)

    mark(ranges, "type_count", len(writer.data), 4)
    writer.i32(1)
    write_serialized_type(writer, version, ranges=ranges)

    big_id_enabled = version == 8
    big_id_raw = 0x12345678 if big_id_enabled else 0
    if 7 <= version < 14:
        writer.i32(big_id_raw)

    mark(ranges, "object_count", len(writer.data), 4)
    writer.i32(1)
    if big_id_enabled:
        path_id = 0x000000010000002A
        mark(ranges, "object_path_id", len(writer.data), 8)
        writer.i64(path_id)
    elif version < 14:
        path_id = 42
        mark(ranges, "object_path_id", len(writer.data), 4)
        writer.i32(path_id)
    else:
        path_id = 42
        writer.align(4)
        mark(ranges, "object_path_id", len(writer.data), 8)
        writer.i64(path_id)

    mark(ranges, "object_byte_start", len(writer.data), 8 if version >= 22 else 4)
    if version >= 22:
        writer.i64(0)
    else:
        writer.u32(0)
    mark(ranges, "object_byte_size", len(writer.data), 4)
    writer.u32(4)

    raw_type_reference = 0 if version >= 16 else (0x13572468 if version == 8 else 28)
    mark(ranges, "object_raw_type_reference", len(writer.data), 4)
    writer.i32(raw_type_reference)
    if version < 16:
        mark(ranges, "object_class_id", len(writer.data), 2)
        writer.u16(28)

    destroyed = None
    script_type_index = None
    stripped = None
    if version < 11:
        destroyed = 0x1234
        mark(ranges, "object_destroyed", len(writer.data), 2)
        writer.u16(destroyed)
    if 11 <= version < 17:
        script_type_index = -3
        mark(ranges, "object_script_type_index", len(writer.data), 2)
        writer.i16(script_type_index)
    if version in (15, 16):
        stripped = True
        mark(ranges, "object_stripped", len(writer.data), 1)
        writer.u8(1)

    if version >= 11:
        mark(ranges, "script_count", len(writer.data), 4)
        writer.i32(0)

    mark(ranges, "external_count", len(writer.data), 4)
    writer.i32(1)
    write_external(writer, version)

    ref_type_count = 1 if version >= 20 else 0
    if version >= 20:
        mark(ranges, "ref_type_count", len(writer.data), 4)
        writer.i32(ref_type_count)
        write_serialized_type(writer, version, ref_type=True)

    user_information = "fixture-user" if version >= 5 else None
    if user_information is not None:
        writer.cstring(user_information)

    expected = {
        "path_id": path_id,
        "raw_type_reference": raw_type_reference,
        "class_id": 28,
        "serialized_type_index": 0 if version >= 16 else None,
        "destroyed": destroyed,
        "script_type_index": script_type_index,
        "stripped": stripped,
        "big_id_enabled": big_id_enabled,
        "big_id_raw": big_id_raw if 7 <= version < 14 else None,
        "user_information": user_information,
        "ref_type_count": ref_type_count,
    }
    expected["metadata_field_ranges"] = ranges
    return bytes(writer.data), expected


def build_fixture(version: int) -> tuple[bytes, dict[str, object]]:
    big_endian = version in (8, 22)
    metadata, expected = build_metadata(version, big_endian=big_endian)
    payload = bytes((version & 0xFF, 0xAA, 0xBB, 0xCC))
    header = WireWriter(True)

    if version < 9:
        data_offset = 128
        metadata_size = 1 + len(metadata)
        file_size = data_offset + len(payload) + metadata_size
        header.u32(metadata_size)
        header.u32(file_size)
        header.u32(version)
        header.u32(data_offset)
        output = bytearray(header.data)
        output.extend(bytes(data_offset - len(output)))
        output.extend(payload)
        output.append(1 if big_endian else 0)
        output.extend(metadata)
    else:
        header_size = 48 if version >= 22 else 20
        data_offset = header_size + len(metadata)
        data_offset += (-data_offset) % 16
        file_size = data_offset + len(payload)
        if version >= 22:
            header.u32(0)
            header.u32(0)
            header.u32(version)
            header.u32(0)
            header.u8(1 if big_endian else 0)
            header.raw(RESERVED)
            header.u32(len(metadata))
            header.i64(file_size)
            header.i64(data_offset)
            header.i64(0x0112233445566778)
        else:
            header.u32(len(metadata))
            header.u32(file_size)
            header.u32(version)
            header.u32(data_offset)
            header.u8(1 if big_endian else 0)
            header.raw(RESERVED)
        output = bytearray(header.data)
        output.extend(metadata)
        output.extend(bytes(data_offset - len(output)))
        output.extend(payload)

    metadata_body_start = (
        data_offset + len(payload) + 1 if version < 9 else header_size
    )
    relative_ranges = expected.pop("metadata_field_ranges")
    absolute_fields = {
        name: {
            "offset": metadata_body_start + field["metadata_offset"],
            "size": field["size"],
        }
        for name, field in relative_ranges.items()
    }
    expected.update(
        {
            "version": version,
            "endian": 1 if big_endian else 0,
            "reserved": list(RESERVED) if version >= 9 else [0, 0, 0],
            "unknown": 0x0112233445566778 if version >= 22 else 0,
            "payload_hex": payload.hex(),
            "type_hash_hex": TYPE_HASH.hex() if version >= 13 else None,
            "ranges": {
                "header": {"offset": 0, "size": 16 if version < 9 else header_size},
                "metadata": {
                    "offset": metadata_body_start - (1 if version < 9 else 0),
                    "size": len(metadata) + (1 if version < 9 else 0),
                },
                "metadata_fields": absolute_fields,
                "payload": {"offset": data_offset, "size": len(payload)},
            },
        }
    )
    return bytes(output), expected


def build_multi_object_fixture(version: int) -> tuple[bytes, list[dict[str, object]]]:
    if version not in (15, 22):
        raise ValueError(f"unsupported multi-object fixture version: {version}")

    big_endian = version == 22
    payloads = (
        bytes((0xA1, 0xA2, 0xA3, 0xA4)),
        bytes((0xB1, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6)),
    )
    payload_offsets = (0, 8)
    payload_stream = bytearray(payloads[0])
    payload_stream.extend(bytes(payload_offsets[1] - len(payload_stream)))
    payload_stream.extend(payloads[1])

    metadata = WireWriter(big_endian)
    metadata.cstring("2020.1.0f1")
    metadata.i32(13)
    metadata.u8(1)
    metadata.i32(1)
    write_serialized_type(metadata, version)
    metadata.i32(len(payloads))

    expected_objects: list[dict[str, object]] = []
    for index, (payload, payload_offset) in enumerate(zip(payloads, payload_offsets)):
        path_id = 42 + index * 42
        metadata.align(4)
        metadata.i64(path_id)
        if version >= 22:
            metadata.i64(payload_offset)
        else:
            metadata.u32(payload_offset)
        metadata.u32(len(payload))
        metadata.i32(0 if version >= 16 else 28)
        if version < 16:
            metadata.u16(28)
        if 11 <= version < 17:
            metadata.i16(-3)
        if version in (15, 16):
            metadata.u8(1)
        expected_objects.append(
            {
                "path_id": path_id,
                "payload_hex": payload.hex(),
                "raw_type_reference": 0 if version >= 16 else 28,
            }
        )

    metadata.i32(0)
    metadata.i32(1)
    write_external(metadata, version)
    if version >= 20:
        metadata.i32(1)
        write_serialized_type(metadata, version, ref_type=True)
    metadata.cstring("multi-object-fixture")

    header_size = 48 if version >= 22 else 20
    data_offset = header_size + len(metadata.data)
    data_offset += (-data_offset) % 16
    file_size = data_offset + len(payload_stream)
    header = WireWriter(True)
    if version >= 22:
        header.u32(0)
        header.u32(0)
        header.u32(version)
        header.u32(0)
        header.u8(1 if big_endian else 0)
        header.raw(RESERVED)
        header.u32(len(metadata.data))
        header.i64(file_size)
        header.i64(data_offset)
        header.i64(0x0112233445566778)
    else:
        header.u32(len(metadata.data))
        header.u32(file_size)
        header.u32(version)
        header.u32(data_offset)
        header.u8(1 if big_endian else 0)
        header.raw(RESERVED)

    output = bytearray(header.data)
    output.extend(metadata.data)
    output.extend(bytes(data_offset - len(output)))
    output.extend(payload_stream)
    return bytes(output), expected_objects


def build_legacy_monobehaviour_fixture() -> bytes:
    version = 15
    metadata = WireWriter(False)
    metadata.cstring("5.4.0f3")
    metadata.i32(13)
    metadata.u8(1)
    metadata.i32(1)
    write_serialized_type(
        metadata,
        version,
        class_id_override=-1,
        script_id_override=LEGACY_SCRIPT_ID,
    )
    metadata.i32(1)
    metadata.align(4)
    metadata.i64(77)
    metadata.u32(0)
    metadata.u32(4)
    metadata.i32(-1)
    metadata.u16(114)
    metadata.i16(7)
    metadata.u8(1)
    metadata.i32(0)
    metadata.i32(0)
    metadata.cstring("legacy-script-fixture")

    payload = bytes((0x78, 0x56, 0x34, 0x12))
    header_size = 20
    data_offset = header_size + len(metadata.data)
    data_offset += (-data_offset) % 16
    file_size = data_offset + len(payload)

    header = WireWriter(True)
    header.u32(len(metadata.data))
    header.u32(file_size)
    header.u32(version)
    header.u32(data_offset)
    header.u8(0)
    header.raw(RESERVED)

    output = bytearray(header.data)
    output.extend(metadata.data)
    output.extend(bytes(data_offset - len(output)))
    output.extend(payload)
    return bytes(output)


def main() -> None:
    repo_root = Path(__file__).resolve().parents[1]
    output_dir = (
        repo_root
        / "crates"
        / "unity-asset-write"
        / "tests"
        / "fixtures"
        / "serialized_file_wire"
    )
    output_dir.mkdir(parents=True, exist_ok=True)

    cases = []
    for version in VERSIONS:
        fixture, expected = build_fixture(version)
        file_name = f"v{version}.assets.bin"
        (output_dir / file_name).write_bytes(fixture)
        cases.append(
            {
                "file": file_name,
                "length": len(fixture),
                "sha256": hashlib.sha256(fixture).hexdigest(),
                "expected": expected,
            }
        )

    legacy_script_file = "legacy_v15_monobehaviour.assets.bin"
    legacy_script_fixture = build_legacy_monobehaviour_fixture()
    (output_dir / legacy_script_file).write_bytes(legacy_script_fixture)

    multi_object_cases = []
    for version in (15, 22):
        fixture, expected_objects = build_multi_object_fixture(version)
        file_name = f"multi_v{version}.assets.bin"
        (output_dir / file_name).write_bytes(fixture)
        multi_object_cases.append(
            {
                "file": file_name,
                "length": len(fixture),
                "sha256": hashlib.sha256(fixture).hexdigest(),
                "purpose": "Single-object edit preserves the untouched object wire identity",
                "expected_objects": expected_objects,
            }
        )

    manifest = {
        "schema": 1,
        "generator": "scripts/generate_serialized_file_goldens.py",
        "oracles": [
            "repo-ref/UnityPy/UnityPy/files/SerializedFile.py",
            "repo-ref/UnityPy/UnityPy/files/ObjectReader.py",
            "repo-ref/UnityPy/UnityPy/helpers/TypeTreeNode.py",
            "repo-ref/assetripper/Source/AssetRipper.IO.Files/SerializedFiles/Parser/SerializedFileMetadata.cs",
            "repo-ref/assetripper/Source/AssetRipper.IO.Files/SerializedFiles/Parser/ObjectInfo.cs",
        ],
        "differential_verification": {
            "implementation": "UnityPy 1.25.2 (vendored commit 5567c5e)",
            "observation": "All generated fixtures parse with one type and one object.",
            "scope_limit": (
                "The synthetic v16 fixture validates the index-only example accepted by UnityPy; "
                "it does not settle the conflicting general v16 raw32 interpretation."
            ),
        },
        "evidence_limits": [
            (
                "The v2/v3 legacy node deltas follow UnityPy 1.25.2 and AssetStudio. "
                "Current AssetRipper applies one legacy layout and is not an oracle for those deltas."
            ),
            (
                "The v16 raw32 value is intentionally index-only in this synthetic case. "
                "UnityPy, AssetStudio, and AssetsTools.NET disagree with AssetRipper and uTinyRipper; "
                "only a Unity-authored 5.5 fixture can settle the general encoding."
            ),
        ],
        "cases": cases,
        "multi_object_cases": multi_object_cases,
        "special_cases": [
            {
                "file": legacy_script_file,
                "length": len(legacy_script_fixture),
                "sha256": hashlib.sha256(legacy_script_fixture).hexdigest(),
                "purpose": "Legacy raw type ID resolves to a MonoBehaviour class-bit identity",
            }
        ],
    }
    (output_dir / "manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )


if __name__ == "__main__":
    main()
